server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/bitcoin/ {
        proxy_pass http://bitcoind:18443/;
        proxy_set_header Content-Type application/json;
    }

    location /api/bitcoin-wallet/ {
        proxy_pass http://bitcoind:18443/wallet/miner;
        proxy_set_header Content-Type application/json;
    }

    location /api/lnd/ {
        proxy_pass https://lnd:8080/;
        proxy_ssl_verify off;
    }

    location /api/fedimint/ {
        proxy_pass http://fedimintd:8174/;
    }

    location /api/gateway/ {
        proxy_pass http://gatewayd:8176/;
    }
}
